# Form implementation generated from reading ui file 'audioPlayerUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AudioPlayerUI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(536, 76)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.currentAudioPos = QtWidgets.QLabel(Dialog)
        self.currentAudioPos.setObjectName("currentAudioPos")
        self.horizontalLayout.addWidget(self.currentAudioPos)
        self.audioPosSlider = QtWidgets.QSlider(Dialog)
        self.audioPosSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.audioPosSlider.setObjectName("audioPosSlider")
        self.horizontalLayout.addWidget(self.audioPosSlider)
        self.audioDuration = QtWidgets.QLabel(Dialog)
        self.audioDuration.setObjectName("audioDuration")
        self.horizontalLayout.addWidget(self.audioDuration)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.currentVolume = QtWidgets.QLabel(Dialog)
        self.currentVolume.setObjectName("currentVolume")
        self.horizontalLayout_2.addWidget(self.currentVolume)
        self.volumeSlider = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        self.maxVolume = QtWidgets.QLabel(Dialog)
        self.maxVolume.setObjectName("maxVolume")
        self.horizontalLayout_2.addWidget(self.maxVolume)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.playBtn = QtWidgets.QPushButton(Dialog)
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_2.addWidget(self.playBtn)
        self.pauseBtn = QtWidgets.QPushButton(Dialog)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_2.addWidget(self.pauseBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "进度"))
        self.currentAudioPos.setText(_translate("Dialog", "00:00"))
        self.audioDuration.setText(_translate("Dialog", "01:00"))
        self.label_3.setText(_translate("Dialog", "音量"))
        self.currentVolume.setText(_translate("Dialog", "50%"))
        self.maxVolume.setText(_translate("Dialog", "100%"))
        self.playBtn.setText(_translate("Dialog", "开始"))
        self.pauseBtn.setText(_translate("Dialog", "暂停"))
