# Form implementation generated from reading ui file 'ProjectDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class ProjectUI(object):
    def setupUi(self, projects):
        projects.setObjectName("projects")
        projects.resize(280, 480)
        self.horizontalLayout = QtWidgets.QHBoxLayout(projects)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.projectListView = QtWidgets.QListView(projects)
        self.projectListView.setObjectName("projectListView")
        self.horizontalLayout.addWidget(self.projectListView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openProjBtn = QtWidgets.QPushButton(projects)
        self.openProjBtn.setObjectName("openProjBtn")
        self.verticalLayout.addWidget(self.openProjBtn)
        self.delProjBtn = QtWidgets.QPushButton(projects)
        self.delProjBtn.setObjectName("delProjBtn")
        self.verticalLayout.addWidget(self.delProjBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(projects)
        QtCore.QMetaObject.connectSlotsByName(projects)

    def retranslateUi(self, projects):
        _translate = QtCore.QCoreApplication.translate
        projects.setWindowTitle(_translate("projects", "项目..."))
        self.openProjBtn.setText(_translate("projects", "打开项目"))
        self.delProjBtn.setText(_translate("projects", "删除项目"))
